#!/bin/sh

# using sed, we filter the bookmarks and remove their protocol
# then we pipe them into a dmenu-like program, mine is called launcher

url=$(sed -e "s|^$LARIZA_HOME_URI$||g" -e 's|^[a-z]*://||g' -e '/^$/d' "$HOME/.cache/lariza/bookmarks" | launcher)

# Then, if we have selected something, open it
[ -z $url ] || cgull "https://$url"
