#!/bin/sh

applications="\
yt2mpv
pdf
firefox
bookmark
youtube-dl
deemix
ex-audio
chromium
"

application=$(printf "$applications" | launcher)

echo "$1" >> "$LARIZA_HISTORY_FILE"

[ -z $application ] || riverctl cgull "$application $1"
